// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {conference} from '../models';
import {audio} from '../models';
import {settings} from '../models';
import {timer} from '../models';

export function ConfirmConferenceJoined():Promise<void>;

export function ConnectConference(arg1:string,arg2:string):Promise<conference.State>;

export function DisconnectConference():Promise<void>;

export function DismissAlert():Promise<void>;

export function GetAudioDevices():Promise<Array<audio.Device>>;

export function GetConferencePlatforms():Promise<Array<conference.Platform>>;

export function GetConferenceState():Promise<conference.State>;

export function GetSettings():Promise<settings.Settings>;

export function GetSounds():Promise<Array<audio.Sound>>;

export function GetState():Promise<timer.Snapshot>;

export function GoToQuestions():Promise<void>;

export function ImportSound():Promise<audio.Sound>;

export function NextSpeaker():Promise<void>;

export function Pause():Promise<void>;

export function PreviewSound(arg1:string):Promise<void>;

export function Reset():Promise<void>;

export function SaveSettings(arg1:settings.Settings):Promise<void>;

export function Start():Promise<void>;

export function TestConferenceSound(arg1:string):Promise<void>;
