// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ConfirmConferenceJoined() {
  return window['go']['main']['App']['ConfirmConferenceJoined']();
}

export function ConnectConference(arg1, arg2) {
  return window['go']['main']['App']['ConnectConference'](arg1, arg2);
}

export function DisconnectConference() {
  return window['go']['main']['App']['DisconnectConference']();
}

export function DismissAlert() {
  return window['go']['main']['App']['DismissAlert']();
}

export function GetAppInfo() {
  return window['go']['main']['App']['GetAppInfo']();
}

export function GetAudioDevices() {
  return window['go']['main']['App']['GetAudioDevices']();
}

export function GetConferenceDiagnostics() {
  return window['go']['main']['App']['GetConferenceDiagnostics']();
}

export function GetConferencePlatforms() {
  return window['go']['main']['App']['GetConferencePlatforms']();
}

export function GetConferenceState() {
  return window['go']['main']['App']['GetConferenceState']();
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function GetSounds() {
  return window['go']['main']['App']['GetSounds']();
}

export function GetState() {
  return window['go']['main']['App']['GetState']();
}

export function GoToQuestions() {
  return window['go']['main']['App']['GoToQuestions']();
}

export function ImportSound() {
  return window['go']['main']['App']['ImportSound']();
}

export function NextSpeaker() {
  return window['go']['main']['App']['NextSpeaker']();
}

export function Pause() {
  return window['go']['main']['App']['Pause']();
}

export function PreviewSound(arg1) {
  return window['go']['main']['App']['PreviewSound'](arg1);
}

export function Reset() {
  return window['go']['main']['App']['Reset']();
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function Start() {
  return window['go']['main']['App']['Start']();
}

export function TestConferenceSound(arg1) {
  return window['go']['main']['App']['TestConferenceSound'](arg1);
}
